version: '3.8'

networks:
  zenit_network:
    driver: bridge

services:
  # === Banco de Dados PostgreSQL ===
  db:
    image: postgres:14-alpine
    container_name: zenit-db
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-senha}
      - POSTGRES_DB=zenit
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./scripts/init-schemas.sql:/docker-entrypoint-initdb.d/1-init-schemas.sql
    networks:
      - zenit_network

  # === Core Backend (API de Autenticação/Autorização) ===
  core-backend:
    build:
      context: ./core-backend
      dockerfile: Dockerfile
    container_name: zenit-core-backend
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://${DB_USER:-postgres}:${DB_PASSWORD:-senha}@db:5432/zenit?schema=core
      - PORT=3000
      - JWT_SECRET=myjwtsecret
    depends_on:
      - db
    networks:
      - zenit_network

  # === Core Frontend (Admin/Autenticação) ===
  core-frontend:
    build:
      context: ./core-frontend
      dockerfile: Dockerfile
    container_name: zenit-core-frontend
    ports:
      - '3001:3000'
    environment:
      - NEXT_PUBLIC_API_URL=http://core-backend:3000/api
    depends_on:
      - core-backend
    networks:
      - zenit_network

  # === Zenit Backend (API Financeira) ===
  zenit-backend:
    build:
      context: ./zenit-backend
      dockerfile: Dockerfile
    container_name: zenit-backend
    ports:
      - '3010:3000'
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://${DB_USER:-postgres}:${DB_PASSWORD:-senha}@db:5432/zenit?schema=zenit
      - CORE_API_URL=http://core-backend:3000/api
      - PORT=3000
      - JWT_SECRET=myjwtsecret
    depends_on:
      - db
      - core-backend
    networks:
      - zenit_network

  # === Zenit Frontend (App Financeiro) ===
  zenit-frontend:
    build:
      context: ./zenit-frontend
      dockerfile: Dockerfile
    container_name: zenit-frontend
    ports:
      - '3011:3000'
    environment:
      - NEXT_PUBLIC_API_URL=http://zenit-backend:3000/api
      - NEXT_PUBLIC_CORE_API_URL=http://core-backend:3000/api
    depends_on:
      - zenit-backend
    networks:
      - zenit_network

volumes:
  postgres-data: