version: '3.8'
services:
  app:
    build: .
    container_name: zenit-core-app
    ports:
      - "3000:3000"          # Mapeia a porta 3000 do container para a porta 3000 do host
    environment:
      - PORT=3000
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    container_name: zenit-db
    restart: always
    ports:
      - "5432:5432"          # Mapeia a porta padrão do PostgreSQL para o host
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=zenit
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
